SELECT ANIMAL_ID, NAME
FROM (
    SELECT AO.ANIMAL_ID, AI.NAME AS NAME, 
           TIMESTAMPDIFF(SECOND, AI.DATETIME, AO.DATETIME) AS TimeDiff
    FROM ANIMAL_INS AI
    JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
) AS SubQuery
ORDER BY TimeDiff DESC
LIMIT 2;
