SELECT T1.Q AS USER_ID, T1.W AS NICKNAME, T1.E AS TOTAL_SALES
FROM    (SELECT B.USER_ID AS Q, B.NICKNAME AS W, SUM(A.PRICE) AS E FROM USED_GOODS_BOARD A
            JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
              WHERE A.STATUS = 'DONE'
            GROUP BY A.WRITER_ID
        ) AS T1
WHERE E >= 700000
ORDER BY 3 ASC;
