SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR
    ,(SELECT MAX(SIZE_OF_COLONY)
     FROM ECOLI_DATA
     WHERE YEAR(DIFFERENTIATION_DATE) = YEAR) - SIZE_OF_COLONY AS YEAR_DEV
     ,ID
FROM ECOLI_DATA 
ORDER BY 1,2 ASC;

# SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
#        MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY
# FROM ECOLI_DATA
# GROUP BY YEAR(DIFFERENTIATION_DATE)
# ORDER BY YEAR;

