SELECT DISTINCT(A.CAR_ID) FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
WHERE 1=1
AND A.CAR_TYPE = '세단'
AND EXTRACT(MONTH FROM START_DATE) = 10
ORDER BY 1 DESC;