SELECT COUNT(T1.C) AS FISH_COUNT, MAX(T1.C) AS MAX_LENGTH, T1.B AS FISH_TYPE
FROM (
    SELECT ID AS A, FISH_TYPE AS B, IFNULL(LENGTH,10) AS C, TIME AS D
    FROM FISH_INFO
) T1
GROUP BY T1.B HAVING AVG(T1.C) >= 33.3
ORDER BY 3;
